FROM openjdk:8
MAINTAINER rahul
EXPOSE 8081
WORKDIR /home/eco-mail/git/learn1/learn11
ADD ./target/learn11-0.0.1-SNAPSHOT.jar /home/eco-mail/rahul/learn.jar
ENTRYPOINT ["java","-jar","/home/eco-mail/rahul/learn1.jar"]
